version: "3.1"
services:
  zerotier:
    image: zyclonite/zerotier:1.10.6
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ztnet
      POSTGRES_PASSWORD: ztnet
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: "http://localhost:3000" # change localhost to your domain or server ip address if hosting on a server.
      NEXTAUTH_SECRET: "random_secret" # change this to a random string of characters.
    networks:
      - app-network
    depends_on:
      - zerotier

volumes:
  zerotier:
  postgres-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
