version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ztnet_dev
      POSTGRES_PASSWORD: ztnet_dev
      POSTGRES_DB: ztnet_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  # zt container
  zerotier:
    image: zyclonite/zerotier:1.12.1

  # ztnet
  ztnet:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
      
    working_dir: /workspaces
    volumes:
      - .:/workspaces:cached
    environment:
      NEXTAUTH_URL: "http://10.0.0.217:3000" # Update this to the URL of your dev environment
      POSTGRES_HOST: postgres
      POSTGRES_USER: ztnet_dev
      POSTGRES_PASSWORD: ztnet_dev
      POSTGRES_DB: ztnet_dev
    networks:
      - app-network
    depends_on:
      - zerotier
